### ISSUE TITLE
running generator

### ISSUE THREAD

**Issue by oluowoj** [dpiponi/quine-central#2]
Could someone please tell me how to run this code?

**Comment by dpiponi** [comment]
If you're running under Linux or OSX and have interpreters for all of the relevant languages installed then you can use `bash test.sh` on the command line. Chances are you don't have them all installed.

To start you can install the Haskell compiler GHC. There are many websites that discuss this. Once you have that installed you should have a command `runghc` in your path. Then you can type `runghc quineCentral.hs` on the command line. The output will be the quine itself. Save that output to a file, maybe with the name `quine.hs`. Now you can run that with `runghc quine.hs`. The output will be a ruby program. Save it as `quine.rb`. Install ruby. Now you can run `ruby quine.rb`. And now just keep going. But it's easier to install compilers for all of the languages and run `test.sh`. 

If you're having trouble installing all of the compilers and interpreters, modify lines 3 onwards in `quineCentral.hs` so the list only includes languages you do have installed. You can tweak `test.sh` to match.

I'll copy these instructions to the README as well.

**Comment by oluowoj** [comment]
Thanks a lot
